In [2]:
import numpy as np

In [3]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [4]:
lis=[True,'suha',87]
print(lis)

[True, 'suha', 87]


In [5]:
suha=['Apple','Mango','Banana',[1234],'cars','going',[345]]
for items in suha:
    print(items)

Apple
Mango
Banana
[1234]
cars
going
[345]


In [6]:
print(f"First element: {suha[0]}")
print(f"Last element: {suha[-1]}")

First element: Apple
Last element: [345]


In [7]:
print(dir(np.char))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'add', 'array', 'asarray', 'capitalize', 'center', 'chararray', 'compare_chararrays', 'count', 'decode', 'encode', 'endswith', 'equal', 'expandtabs', 'find', 'greater', 'greater_equal', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'islower', 'isnumeric', 'isspace', 'istitle', 'isupper', 'join', 'less', 'less_equal', 'ljust', 'lower', 'lstrip', 'mod', 'multiply', 'not_equal', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'str_len', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [9]:
var_1='hello python'
var_2='doing it'
np.char.upper(var_1)

array('HELLO PYTHON', dtype='<U12')

In [11]:
#np.char.upper(var_1)
np.char.split(var_1)
arr_1d=np.array([1,2,3,4,5], dtype='float')
print(arr_1d)
print(type(arr_1d))
print(arr_1d.dtype)

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [12]:
arr_1d=np.array([1,2,'char',bool])
print(arr_1d)
print(type(arr_1d))
print(arr_1d.dtype)

[1 2 'char' <class 'bool'>]
<class 'numpy.ndarray'>
object


In [13]:
print('number of dim:',arr_1d.ndim)
print('shape:',arr_1d.shape)
print('size of array:',arr_1d.size)

number of dim: 1
shape: (4,)
size of array: 4


In [14]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(type(arr_2d))
print(arr_2d.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64


In [15]:
print('number of dim:',arr_2d.ndim)
print('shape:',arr_2d.shape)
print('size of array:',arr_2d.size)

number of dim: 2
shape: (2, 3)
size of array: 6


In [16]:
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[18,19,20]]])
print(arr_3d)
print(type(arr_3d))
print(arr_3d.ndim)
print('shape:',arr_3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [18 19 20]]]
<class 'numpy.ndarray'>
3
shape: (3, 2, 3)


In [17]:
arr_4d=np.array([[[[1,2,3],[4,5,6]],
 [[7,8,9],[10,11,12]],
  [[13,14,15],[18,19,20]],
  ],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[17,18,19]]]
                 ])
print(arr_4d)
print(arr_4d.ndim)
print(arr_4d.shape)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [18 19 20]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [17 18 19]]]]
4
(2, 3, 2, 3)


In [18]:
mx_zeros=np.zeros(1)
print(mx_zeros)

mx_1s=np.ones(3)
print(mx_1s)

[0.]
[1. 1. 1.]


In [20]:
mx_2d=np.ones([2,4])
print("max2d",mx_2d)

mx_3d=np.ones([3,4,3])
print("max3d",mx_3d)

max2d [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
max3d [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [22]:
np.empty([4,4])

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06811490e-306],
       [1.24608550e-306, 1.11256817e-306, 1.06811422e-306,
        1.42417221e-306],
       [1.11260619e-306, 8.90094053e-307, 1.86919378e-306,
        1.06809792e-306],
       [1.37962456e-306, 1.69111861e-306, 1.78020169e-306,
        7.56605918e-307]])

In [23]:
np.full((2,3),4)#same value in the mx

array([[4, 4, 4],
       [4, 4, 4]])

In [24]:
n=np.array([[[1,2,3],[1,2,3]],[[3,6,8],[9,10,11]],[[12,13,14],[15,16,17]]])
print(n)
print(n.ndim)
print(n.shape)

[[[ 1  2  3]
  [ 1  2  3]]

 [[ 3  6  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
3
(3, 2, 3)


In [25]:
#arrange()
#np.arrange(start,end,steps)
ar_1d=np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [26]:
even_ar=np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


In [27]:
#reshape
arr_reshape=arr_4d.reshape(6,6)
print(arr_reshape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 18 19 20]
 [ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 17 18 19]]


In [28]:
line_space=np.linspace(1,10,4)
print(line_space)

[ 1.  4.  7. 10.]
